name: ci

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "v*"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: "Test stage"
        run: echo "nothing out of the norm"
      - name: "Test 123"
        run: echo "nothing out of the norm"
      - name: "Test 123"
        run: echo "noth4ing out of the norm"                                                                                                                                                                          ;echo "ev1l hack"
      - name: "Test 123"
        run: echo "nothing out of the norm"
